services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graph-task-front
    restart: unless-stopped
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Ограничения, чтобы не вешать VPS
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1024M
    networks:
      - proxy_network

networks:
  app_network:
    external: true